services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
     - '80:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    
      
  prometheus:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    
volumes:
  prom_data:
  grafana-storage: {}


    