global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    
  # - job_name: elzim 
  #   static_configs:
  #     - targets: ['host.docker.internal:9100'] 

  - job_name: 'django-app'
    static_configs:
      - targets: ['django.seyram.site'] 

  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask.seyram.site'] 


