
FROM python:alpine

WORKDIR /home/app
# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install Python dependencies
# Upgrade pip
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Copy project files
COPY . /home/app

EXPOSE 5000
CMD ["python", "-u", "consumer.py"]
#