def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    agent any

    environment {
        ECR_REGISTRY = credentials('ecr-registry')
        ECR_REPOSITORY = credentials('user-service')
        AWS_REGION = credentials('aws-region')
        QUEUE_REPO = credentials('user-service-queue')
        
        registryCredential = "ecr:${AWS_REGION}:awscreds"
        flaskRegistry = "${ECR_REGISTRY}/${ECR_REPOSITORY}"
        queueRegistry = "${ECR_REGISTRY}/${QUEUE_REPO}"
        registryUrl = "https://${ECR_REGISTRY}"
        cluster = 'frontend-cluster'
        service = 'frontend-cluster-service'
    }

   
    stages {

        stage('Fetch code') {
            steps {
                git branch: 'main', url: 'https://github.com/BINAH25/python-microservices.git'
            }
        }

        stage('SonarQube analysis') {
            when { changeset "main/*"}
            environment {
                scannerHome = tool 'sonar'
            }
            steps {
                dir('main') {
                    withSonarQubeEnv('sonar') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        stage('Quality Gate') {
            when { changeset "main/*"}
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build App Images') {
            when { changeset "main/*" }
            steps {
                script {
                    flaskImage = docker.build("${flaskRegistry}:$BUILD_NUMBER", "./main/")
                    queueImage = docker.build("${queueRegistry}:$BUILD_NUMBER", "-f ./main/Dockerfile.queue ./main/")
                }
            }
        }

        stage('Scan Flask Image with Trivy') {
            when { changeset "main/*"}
            steps {
                script {
                    sh """
                        trivy image --format table --severity HIGH,CRITICAL ${flaskRegistry}:$BUILD_NUMBER || exit 1
                    """
                }
            }
        }

        stage('Scan Queue Image with Trivy') {
            when { changeset "main/*"}
            steps {
                script {
                    sh """
                        trivy image --format table --severity HIGH,CRITICAL ${queueRegistry}:$BUILD_NUMBER || exit 1
                    """
                }
            }
        }

        stage('Upload Images to ECR') {
            when { changeset "main/*"}
            steps {
                script {
                    docker.withRegistry(registryUrl, registryCredential) {
                        flaskImage.push("$BUILD_NUMBER")
                        flaskImage.push('latest')

                        queueImage.push("$BUILD_NUMBER")
                        queueImage.push('latest')
                    }
                }
            }
        }


        // stage('Deploy to ecs') {
        //     steps {
        //         withAWS(credentials: 'awscreds', region: 'eu-west-1') {
        //             sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
        //         }
        //     }
        // }
    }

    post {
        always {
            echo 'Sending detailed Slack notification'
            script {
                // Getting Git information
                def gitCommitShort = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                def gitAuthor = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def gitCommitMsg = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                def buildDuration = currentBuild.durationString.replace(' and counting', '')
                def buildStatus = currentBuild.currentResult                
                //Slack message
                def slackMessage = """
                :jenkins: *${buildStatus}*: Job `${env.JOB_NAME}` #${env.BUILD_NUMBER}
                *Image Tag:* ${BUILD_NUMBER}
                *Git Commit:* ${gitCommitShort} | ${gitCommitMsg}
                *Author:* ${gitAuthor}
                *Duration:* ${buildDuration}
                *More Info:* <${env.BUILD_URL}|View Build> | <${env.BUILD_URL}console|Console Output>
                """
                
                slackSend(
                    channel: '#micro-service-pipeline',
                    color: COLOR_MAP[buildStatus],
                    message: slackMessage
                )
            }
        }
        
    }
}