services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - static_volume:/home/app/staticfiles
    depends_on:
      - db
    networks:
      - shared-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile.queue
    depends_on:
      - db
    networks:
      - shared-network

  db:
    container_name: file_server_db
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db
    ports:
      - "5432:5432"
    networks:
      - shared-network


volumes:
  postgres_data:
  static_volume:

networks:
  shared-network:
    external: true

    